# Importing Numpy

In [1]:
import numpy as np
np.__version__ #Numpy version checking

'1.26.4'

# Fixed-Type Arrays in Python

In [2]:
import array
L = list(range(10))
A = array.array('i',L)
print(A)

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


# Creating Arrays from Python Lists

In [3]:
a = np.array([1, 2, 3, 4, 5])
print(a)

[1 2 3 4 5]


In [4]:
b = np.array([3.14, 3, 2.5, 4, 6]) 
print(b) # Integer value typecasted to float value automatically

[3.14 3.   2.5  4.   6.  ]


In [5]:
# Explicitly converting from one data type to another
c = np.array([3.14, 3, 2.5, 4, 6], dtype = "int32")
print(c)

[3 3 2 4 6]


In [6]:
# Nested lists result in multidimensional array
d = np.array([range(i, i+3) for i in [2, 4, 6]])
print(d)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


# Creating Array from Scratch

In [7]:
# Create a length-10 integer array filled with zeros
a = np.zeros(10, dtype = int)
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [8]:
# Create a 3x5 floating-point array filled with 1's
b = np.ones((3,5), dtype = float)
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
# Create a 3x5 array filled with 3.14
c = np.full((3, 5), 3.14)
print(c)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [10]:
# Creating an array filled with a linear sequence. Starting at 0, ending at 20, stepping by 2.(this is similar to the built-in range() function)
d = np.arange(0, 20, 2)
print(d)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
# Create an array of five values evenly spaced between 0 and 1 
e = np.linspace(0, 1, 5)
print(e)

[0.   0.25 0.5  0.75 1.  ]


In [12]:
# Create a 3x3 array of uniformly distributed random values between 0 and 1
f = np.random.random((3,3)) # It always produce float values between 0 and 1.
print(f)

[[0.63690334 0.62056252 0.00818246]
 [0.60011317 0.09446509 0.40209602]
 [0.02312981 0.21055056 0.97488972]]


In [13]:
# Create a 3x3 array of normally distributed random values with mean 0 and standard deviation 1
g = np.random.normal(0, 1, (3,3)) #[Mean, Standard Deviation, Size] and it can produce any real value.
print(g)

[[ 1.56234819 -0.1261278  -0.71971331]
 [ 1.08623359 -0.53863393  1.25484787]
 [ 0.23306842 -0.91292076 -1.29737104]]


In [14]:
# Create a 3x3 array of random integers in the interval (0,10)
h = np.random.randint(0, 10, (3,3)) #[Start, End, Size] and it produces value from a specified range.
print(h)

[[7 8 1]
 [8 3 4]
 [9 2 9]]


In [15]:
# Create a 3x3 identity matrix
i = np.eye(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
# Create an uninitialized array of three integers. The values will be whatever happens to already exist at that memory loaction
j = np.empty(3)
print(j)

[1. 1. 1.]


# Numpy Standard Data Types

In [17]:
a = np.zeros(10, dtype = "int16")
print(a)

[0 0 0 0 0 0 0 0 0 0]


In [18]:
b = np.ones(10, dtype = np.float32)
print(b)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Numpy Attributes

In [19]:
np.random.seed(0) # Seed for reproducibility

In [20]:
a = np.random.randint(10, size = 6) # 1-D Array
print(a)

[5 0 3 3 7 9]


In [21]:
b = np.random.randint(10, size = (3, 4)) # 2-D Array
print(b)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [22]:
c = np.random.randint(10, size = (3, 4, 5)) # 3-D Array
print(c)

[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]


In [23]:
print(c.ndim) # Dimension
print(c.shape) # Shape
print(c.size) # Size
print(c.dtype) # Data Type

3
(3, 4, 5)
60
int32


In [24]:
print("itemsize:", c.itemsize, "bytes")
print("nbytes:", c.nbytes, "bytes") # nbytes = itemsize(in bytes) * size

itemsize: 4 bytes
nbytes: 240 bytes


# Array Indexing: Accessing Single Elements

In [25]:
print(a)

[5 0 3 3 7 9]


In [26]:
print(a[0]) # First element 

5


In [27]:
print(a[4]) # Fifth element 

7


In [28]:
print(a[-1]) # Last element

9


In [29]:
print(a[-2]) # Second last element

7


In [30]:
print(b)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [31]:
print(b[0, 0]) # First element (Row, Column)

3


In [32]:
print(b[2, 0]) # 3rd row, 1st column

1


In [33]:
print(b[2, -1]) # 3rd row, 3rd column

7


In [34]:
# Modifying the values
b[0, 0] = 12
print(b)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
b[0] = 3.14159 # this will be truncated
print(b)

[[3 3 3 3]
 [7 6 8 8]
 [1 6 7 7]]


# Array Slicing: Accessing Subarrays

In [36]:
#1-D Array
x = np.arange(10)
print(x)
print(x[:5]) # First five elements
print(x[5:]) # elements after index 5
print(x[4:7]) # middle subarray
print(x[::2]) # every other element
print(x[1::2]) # every other element. starting at index 1
print(x[::-1]) # all elements reversed
print(x[5::-2]) # reversed every other from index 5      

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4]
[5 6 7 8 9]
[4 5 6]
[0 2 4 6 8]
[1 3 5 7 9]
[9 8 7 6 5 4 3 2 1 0]
[5 3 1]


In [37]:
# Multidimensional subarrays
print(b)
print(b[:2, :3]) # two rows, three columns
print(b[:3, ::2]) # all rows, every other column
print(b[::-1, ::-1]) # Flip the array both vertically and horizontally (like a 180° rotation)

[[3 3 3 3]
 [7 6 8 8]
 [1 6 7 7]]
[[3 3 3]
 [7 6 8]]
[[3 3]
 [7 8]
 [1 7]]
[[7 7 6 1]
 [8 8 6 7]
 [3 3 3 3]]


In [38]:
# Accessing array rows and columns
print(b[:, 0]) # first column of 'b'
print(b[0, :]) # first row of 'b'
print(b[0]) # equivalent to b[0, :]

[3 7 1]
[3 3 3 3]
[3 3 3 3]


In [39]:
# Subarrays as no-copy views
print(b)

b_sub = b[:2, :2]
print(b_sub)

# If we modify this subarray, then original array will change
b_sub[0, 0] = 99
print(b_sub)

print(b) # Original array is changed

[[3 3 3 3]
 [7 6 8 8]
 [1 6 7 7]]
[[3 3]
 [7 6]]
[[99  3]
 [ 7  6]]
[[99  3  3  3]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [40]:
# Creating copies of arrays
b_sub_copy = b[:2, :2].copy()

# Modifying the subarray
b_sub_copy[0, 0] = 42
print(b_sub_copy)

print(b) # Original array is not changed

[[42  3]
 [ 7  6]]
[[99  3  3  3]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# Reshaping of Arrays

In [43]:
grid = np.arange(1, 10).reshape((3,3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [44]:
# row vector via reshape
a = np.array([1, 2, 3])
print(a.reshape((1,3)))

[[1 2 3]]


In [46]:
# row vector via newaxis
print(a[np.newaxis, :])

[[1 2 3]]


In [48]:
# column vector via reshape
print(a.reshape((3,1)))

[[1]
 [2]
 [3]]


In [49]:
# column vector via newaxis
print(a[:, np.newaxis])

[[1]
 [2]
 [3]]


# Array Concatenation and Splitting

In [56]:
# Concatenation of arrays
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(np.concatenate([x,y]))

[1 2 3 4 5 6]


In [58]:
# Concatenation of more than two arrays 
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
z = np.array([7, 8, 9])
print(np.concatenate([x,y,z]))

[1 2 3 4 5 6 7 8 9]


In [62]:
# Concatenation of 2-D arrays
grid = np.array([[1, 2, 3],[4, 5, 6]])
print(np.concatenate([grid, grid])) # concatenate along the first axis(down the rows -> axis=0)
print(np.concatenate([grid, grid], axis=1)) # concatenate along the second axis(along the columns)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [63]:
# np.vstack function
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the arrays
print(np.vstack([x, grid]))

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [66]:
y = np.array([[99],
              [99]])

# horizontally stack the arrays
print(np.hstack([grid, y]))

[[ 9  8  7 99]
 [ 6  5  4 99]]


In [67]:
# Splitting of arrays
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3,5]) # [First split, Second split]
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [73]:
# Vertical and Horizontal splitting
grid = np.arange(16).reshape((4,4))
print(grid)

# Vertical splitting
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

# Horizontal splitting
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
