# Exploring Numpy's UFuncs

In [2]:
import numpy as np

In [6]:
# Array Arithmetic
x = np.arange(4)
print("x =", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 2 = ", x * 2)
print("x / 2 = ", x / 2)
print("x // 2 = ", x // 2) # floor division

x = [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 2 =  [0 2 4 6]
x / 2 =  [0.  0.5 1.  1.5]
x // 2 =  [0 0 1 1]


In [9]:
# Unary UFuncs -> It operates on single input.
print("-x = ", -x) # Negation
print("x ** 2 = ", x ** 2) # Exponentiation
print("x % 2 = ", x % 2) # Modulus

# Example
print(-(0.5*x + 1) ** 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]
[-1.   -2.25 -4.   -6.25]


In [14]:
# Arithmetic operations using Numpy's Mathematical Functions
print(np.add(x, 2))          # Addition
print(np.subtract(x, 2))     # Subtraction
print(np.multiply(x, 2))     # Multiplication
print(np.divide(x, 2))       # Division
print(np.negative(x))        # Negation
print(np.floor_divide(x, 2)) # Floor Division
print(np.power(x, 2))        # Exponentiation
print(np.mod(x,2))           # Modulus

[2 3 4 5]
[-2 -1  0  1]
[0 2 4 6]
[0.  0.5 1.  1.5]
[ 0 -1 -2 -3]
[0 0 1 1]
[0 1 4 9]
[0 1 0 1]


In [17]:
# Absolute Value(Python built-in function)
x = np.array([-2, -1, 0, 1, 2])
print(abs(x)) 

# Absolute Value(Numpy Function)
print(np.abs(x))

# Complex data(returns the magnitude)
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(np.abs(y))

[2 1 0 1 2]
[2 1 0 1 2]
[5. 5. 2. 1.]


In [27]:
# Trigonometric Functions
theta = np.linspace(0, np.pi, 3)
print("theta = ", theta)
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

# Inverse Trigonometric Functions
y = [-1, 0, 1]
print("y = ", y)
print("arcsin(y) = ", np.arcsin(y))
print("arccos(y) = ", np.arccos(y))
print("arctan(y) = ", np.arctan(y))

theta =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
y =  [-1, 0, 1]
arcsin(y) =  [-1.57079633  0.          1.57079633]
arccos(y) =  [3.14159265 1.57079633 0.        ]
arctan(y) =  [-0.78539816  0.          0.78539816]


In [30]:
# Exponential Functions
x = [1, 2, 3]
print("x = ", x)
print("e^x = ", np.exp(x))
print("2^x = ", np.exp2(x))
print("3^x = ", np.power(3, x))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [31]:
# Logarithmic Functions
x = [1, 2, 4, 10]
print("x = ", x)
print("ln(x) = ", np.log(x)) # Natural log
print("log2(x) = ", np.log2(x))
print("log10(x) = ", np.log10(x))

x =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.38629436 2.30258509]
log2(x) =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [32]:
# Some specialized functions(works on very small input, gives more precise values)
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 = ", np.expm1(x))
print("log(1 + x) = ", np.log1p(x))

exp(x) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) =  [0.         0.0009995  0.00995033 0.09531018]


In [38]:
# Specialized ufuncs
from scipy import special

# Gamma functions (generalized factorials) and related functions
x = [1, 5, 10]
print("gamma(x) = ", special.gamma(x)) # Gamma functions [(n-1)!] always return floating-point number
print("ln|gmma(x)| = ", special.gammaln(x)) # Natural logarithm of the absolute value of the Gamma function
print("beta(x, 2) = ", special.beta(x, 2)) # Beta function

# Error Function (integral of Gaussian)
x = np.array([0, 0.3, 0.7, 1.0])
print("erf(x) = ", special.erf(x))
print("erfc(x) = ", special.erfc(x)) # Complement of error function
print("erfinv(x) = ", special.erfinv(x)) # Inverse of error function

gamma(x) =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gmma(x)| =  [ 0.          3.17805383 12.80182748]
beta(x, 2) =  [0.5        0.03333333 0.00909091]
erf(x) =  [0.         0.32862676 0.67780119 0.84270079]
erfc(x) =  [1.         0.67137324 0.32219881 0.15729921]
erfinv(x) =  [0.         0.27246271 0.73286908        inf]


# Advanced UFunc Features

In [40]:
# Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y) # Storing the output in 'y' instead of creating new array
print(y)

[ 0. 10. 20. 30. 40.]


In [42]:
# Specifying output with array views
y = np.zeros(10)
np.power(2, x , out = y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [46]:
# Aggregates
x = np.arange(1, 6)
# np.add.reduce applies the add function cumulatively to the elements of x,
# effectively summing all the elements step-by-step to produce a single value.
np.add.reduce(x)

15

In [47]:
np.multiply.reduce(x)

120

In [48]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [49]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120])

In [59]:
# Outer Products
x = np.arange(1, 11)

# Compute the outer product of x with itself.
# Result is a 2D array where each element (i, j) = x[i] * x[j]
np.multiply.outer(x, x)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])