# Structured Data: Numpy's Structured Arrays

In [2]:
import numpy as np

In [5]:
data = np.zeros(4, dtype = {"names" : ("name", "age", "weight"),
                            "formats" : ("U10", "i4", "f8")})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [8]:
name = ["Alice", "Bob", "Cathy", "Doug"]
age = [25, 45, 37, 19]
weight = [55.0, 85.5, 68.0, 61.5]

data["name"] = name
data["age"] = age
data["weight"] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [13]:
# In structured arrays we can refer to values either by index or name
print(data["name"])

# Get first row of data
print(data[0])

# Get the name from the last row
print(data[-1]["name"])

# Get names where age is under 30
print(data[data["age"] < 30]["name"])

['Alice' 'Bob' 'Cathy' 'Doug']
('Alice', 25, 55.)
Doug
['Alice' 'Doug']


# Creating Structured Arrays

In [20]:
# Dictionary Method
print(np.dtype({"names" : ("name", "age", "weight"),
          "formats" : ("U10", "i4", "f8")}))

# Numerical types can be specified with Python types or Numpy dtypes
print(np.dtype({"names" : ("name", "age", "weight"),
          "formats" : ((np.str_, 10), int, np.float32)}))

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')]


In [16]:
# Tuple Method
print(np.dtype([("name", "S10"), ("age", "i4"), ("weight", "f8")]))

[('name', 'S10'), ('age', '<i4'), ('weight', '<f8')]


# More Advanced Compound Types

In [22]:
tp = np.dtype([("id", "i8"), ("mat", "f8", (3, 3))])
X = np.zeros(1, dtype = tp)
print(X[0])
print(X["mat"][0])

(0, [[0., 0., 0.], [0., 0., 0.], [0., 0., 0.]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


# RecordArrays: Structured Arrays with a Twist

In [25]:
# Previously accessed the ages by writing
print(data["age"])

# We can also access with slightly fewer keystrokes
data_rec = data.view(np.recarray)
print(data_rec.age)

[25 45 37 19]
[25 45 37 19]
